/*-------------------------------------------------------------------------
 *
 * nr_aiengine_d.h
 *    Macro definitions for nr_aiengine
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef NR_AIENGINE_D_H
#define NR_AIENGINE_D_H

#define NrAiengineRelationId 9600
#define NrAiengineOidIndexId 9601

#define Anum_nr_aiengine_oid 1
#define Anum_nr_aiengine_aieport 2
#define Anum_nr_aiengine_aieaddr 3
#define Anum_nr_aiengine_aiename 4
#define Anum_nr_aiengine_aieconn 5

#define Natts_nr_aiengine 5


#endif							/* NR_AIENGINE_D_H */
