# Make file for the nr_preprocessing module
# It calls the CMakelists.txt file in the same directory

all:
	mkdir -p build
	cd build && cmake ..

install:
	cd build && make install
	cd ..

clean:
	rm -rf build
